// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDsbHEh5P7WYzw_y0LclKYzQDor9Mg0Bc',
    appId: '1:93276430011:web:ca88e888e967f98444539e',
    messagingSenderId: '93276430011',
    projectId: 'petnest-app2',
    authDomain: 'petnest-app2.firebaseapp.com',
    databaseURL: 'https://petnest-app2-default-rtdb.firebaseio.com',
    storageBucket: 'petnest-app2.firebasestorage.app',
    measurementId: 'G-MBX076F8LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYvfb7IpDlVcAkWtlLp8AT_ZN88tCs0kg',
    appId: '1:93276430011:android:85c0decd936363b544539e',
    messagingSenderId: '93276430011',
    projectId: 'petnest-app2',
    databaseURL: 'https://petnest-app2-default-rtdb.firebaseio.com',
    storageBucket: 'petnest-app2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0LbFCkoOHMsaoCqvgxff5W5DYGPyaUc8',
    appId: '1:93276430011:ios:88b46b94fbbca28d44539e',
    messagingSenderId: '93276430011',
    projectId: 'petnest-app2',
    databaseURL: 'https://petnest-app2-default-rtdb.firebaseio.com',
    storageBucket: 'petnest-app2.firebasestorage.app',
    iosBundleId: 'com.example.petnestReal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0LbFCkoOHMsaoCqvgxff5W5DYGPyaUc8',
    appId: '1:93276430011:ios:88b46b94fbbca28d44539e',
    messagingSenderId: '93276430011',
    projectId: 'petnest-app2',
    databaseURL: 'https://petnest-app2-default-rtdb.firebaseio.com',
    storageBucket: 'petnest-app2.firebasestorage.app',
    iosBundleId: 'com.example.petnestReal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDsbHEh5P7WYzw_y0LclKYzQDor9Mg0Bc',
    appId: '1:93276430011:web:e7715b9968c2bd4c44539e',
    messagingSenderId: '93276430011',
    projectId: 'petnest-app2',
    authDomain: 'petnest-app2.firebaseapp.com',
    databaseURL: 'https://petnest-app2-default-rtdb.firebaseio.com',
    storageBucket: 'petnest-app2.firebasestorage.app',
    measurementId: 'G-G9Z2S7XK2T',
  );
}
